Migrate new discord js with minor rework
ChristopherVR/NeinDiscordBot pull request #113
Opened 2023-08-13 07:47 UTC by ChristopherVR

- Refactored files
- Restructured project
- Updated npm packages
- Migrated to latest DiscordJS logic
- Improved stability
- Improved logging messages
- Added stub logger (to be replaced in future with a proper logger)
- Added logic to prevent NodeJS from crashing when an exception is thrown
- Removed magic words (replaced with Enums)
- Reduced default volume to 65%
- Resolved memory leak with multiple Extractors being registered to the discord player
- Improved handling of translations
- Added a few more specific error messages

TODO:
- Convert eslintrc.json to eslint flat config (all other config styles will be deprecated in V9)
- Resolve issue with duplicate commands showing in discord

2023-08-16 20:25 UTC, ElHefe3 commented on src/server/setup.ts
> +  server.get('/', (_, res) => res.sendFile(path.join(path.dirname('/index.html'))));
We can leave this, but we'll have to change it before deploying to a public server.

2023-08-16 20:28 UTC, ElHefe3 commented on src/bot/interactionCreate.ts
> -
Separate external & internal imports

2023-08-16 21:19 UTC, ElHefe3 requested changes
Just fix the test

2023-08-19 11:37 UTC, ChristopherVR commented on src/server/setup.ts
> +  server.get('/', (_, res) => res.sendFile(path.join(path.dirname('/index.html'))));
Rate limit is being send on the line before this one.

2023-10-29 06:50 UTC, ChristopherVR commented
Manually merged.

2023-10-29 06:50 UTC, closed without merging